name: anjelusive
favicon: null
layout_spectrum: 0.49333
typography_spectrum: 0.34008857677690685
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#7f7e7c'
    - '#4d4d4d'
    - '#f3f0ed'
    - '#a5a29e'
  brandStrength: 0.9375
  lightness: 0.7668148698285222
  saturation: 0.6216205819509923
  rhythmicContrast: 0.8852112670429051
purpose: []
