name: anjelusive
favicon: null
layout_spectrum: 0.04056832636706531
typography_spectrum: 0.34008857677690685
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7958342893980443
  lightness: 0.7668148698285222
  saturation: 0.6216205819509923
  rhythmicContrast: 0.8852112670429051
purpose: []
